---
- name: Pull Docker Image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /opt/homebrew/bin/python3
  tasks:
    - name: Pull image
      docker_image:
        name: pink27/calculator:latest
        source: pull
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name Calculator pink27/calculator