---
- name: Pull Docker Image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /Users/vinnie/anaconda3/bin/python3
  tasks:
    - name: Pull image
      docker_image:
        name: pink27/calculator:latest
        source: pull

    - name: Running container
      shell: docker run -it -d --name Calculator pink27/calculator
